create schema if not exists donationDB;
create table donationDB.userInformation (id bigint(20) unsigned NOT NULL,
	firstName varchar(255) NOT NULL, 
    lastName varchar(255) NOT NULL, 
	address varchar(255) NOT NULL, 
    city varchar(255) NOT NULL, 
	state varchar(255) NOT NULL, 
    country varchar(255) NOT NULL, 
	postCode varchar(255) NOT NULL, 
    phone varchar(255) NOT NULL, 
	email varchar(255) NOT NULL, 
    preferredContact varchar(255) NOT NULL, 
	currency varchar(255) NOT NULL, 
    frequency varchar(255) NOT NULL, 
	paymentAmount DECIMAL(65,2) NOT NULL, 
    comments longtext,
    PRIMARY KEY (id));